# Generated by Django 2.0 on 2017-12-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0002_auto_20171213_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('location', 'date_taken', 'name')},
        ),
        migrations.AlterField(
            model_name='location',
            name='information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='archive_manager.Location'),
        ),
    ]
