# Generated by Django 2.0 on 2017-12-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0003_auto_20171225_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
