# Generated by Django 2.0 on 2017-12-25 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0004_auto_20171225_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date_added',
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
