# Generated by Django 2.0.1 on 2018-01-08 09:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0006_auto_20171225_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_file', models.ImageField(upload_to='photos/logos', verbose_name='Logo')),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('zoom_level', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
