# Generated by Django 2.0.1 on 2018-01-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0007_auto_20180108_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='archive_manager.Project'),
            preserve_default=False,
        ),
    ]
