# Generated by Django 2.0 on 2018-01-09 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0008_location_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
