# Generated by Django 2.0 on 2018-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0009_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
