# Generated by Django 2.0.1 on 2018-01-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0010_auto_20180109_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.ImageField(upload_to='photos/local_photos/', verbose_name='Local Photo'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('project', 'name')},
        ),
    ]
