# Generated by Django 2.0.1 on 2018-01-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0012_auto_20180115_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='long_desc',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
    ]
