# Generated by Django 2.0.1 on 2018-01-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0013_photo_long_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='long_desc',
        ),
    ]
