# Generated by Django 2.0.1 on 2018-01-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0014_remove_photo_long_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='long_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
