# Generated by Django 2.0.1 on 2018-01-15 19:49

import archive_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0015_photo_long_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.ImageField(upload_to=archive_manager.models.Photo.get_path, verbose_name='Local Photo'),
        ),
    ]
