# Generated by Django 2.0.1 on 2018-02-08 08:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0016_auto_20180115_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='zoom_level',
        ),
        migrations.AddField(
            model_name='project',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
